<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
  <title>Formmailer</title>
</head>

<body>
<div align="center">

<?php
// Ziel der Postoperation
// diese Seite oder eine Seite welche diese
// included
// ==========================================

$target="formmail.phtml";

// ==========================================


$error="";
// ===================================================================
if ( isset($gesendet)) {
  // $gesendet kann nur nach dem senden des Formulars gesetzt sein
  // --------------------------------------------------------------


  // Formular auswerten
  // =====================================

  // Felder für Fehlermeldung auswerten
  // ======================================
  
  // Felder welche nicht ausgewertet werden sollen 
  // einfach hier mittels // kommentieren
  if ($name=="") { $error .=" Name,";}
  if ($email=="") { $error .=" eMail-Adresse,";}
  if ($plz=="") { $error .=" PLZ,";}
  if ($ort=="") { $error .=" Ort,";}
  if ($strasse=="") { $error .=" Straße,";}
  // if ($telefon=="") { $error .=" Telefonnummer,";}
  if ($comment=="") { $error .=" Ihre Nachricht,";}

  if (! isset($kontakt_1)) {$kontakt_1=0;}
  if (! isset($kontakt_2)) {$kontakt_2=0;}
  if ($kontakt_1==0 && $kontakt_2==0 ) { $error .= " Die gewünschte Art der Kontaktaufnahme,"; }

  
  // Wenn keine Eingabe Fehler aufgetreten
  // sind Bestätigung ausgeben
  // ======================================
  if ($error=="") {
    
    $kontakt_per="  Informieren Sie mich :\n";
    if ($kontakt_1==1) { $kontakt_per .="      per email\n"; }
    if ($kontakt_2==1) { $kontakt_per .="      telefonisch\n"; }
    $kontakt_per .="\n";

    $Nachricht = "Kontakt von:\n";
    $Nachricht .= "  Name:      $name\n";
    $Nachricht .= "  PLZ / Ort: $plz $ort\n";

    $Nachricht .= "  Strasse:   $strasse\n";
    $Nachricht .= "  eMail:     $email\n";
    $Nachricht .= "  Telefon:   $telefon\n\n";
    $Nachricht .= $kontakt_per;
    $Nachricht .= "Inhalt der Nachricht:\n\n";
    $Nachricht .= "$comment\n";

    $Domain=eregi_replace(".*\.([a-z0-9\-]*)\.([a-z]*)$","\\1.\\2",getenv("SERVER_NAME"));
    $Empfaenger = "webmaster@$Domain";

    $subject = "eMail vom Kontaktformular";

    $Header = "From: Kontaktformular <webmaster@$Domain>\n";

    mail($Empfaenger,$subject,$Nachricht,$Header);
?>
    <table cellspacing=0 cellpadding=0 border=0>
      <tr>
        <td>Wir bedanken uns für Ihr Interesse, Ihre Nachricht wird von uns in Kürze bearbeitet.</td>
      </tr>
    </table>

<?php
  // ENDE: if ($error=="")
  }
// ENDE: if gesendet
}
?>



<?php
// Formular nur ausgeben wenn noch nicht gesendet worden ist
// oder wenn ein Eingabefehler vorlag
// ==========================================================
if ($error !="" || (! isset($gesendet)) ) {
  ?>

  <form  action="<?php echo $target; ?>" method=get>
  <input type="hidden" name="gesendet" value="1">
  <table border=0 cellpadding=3 cellspacing=2 width="298">
  <?php
  // Eingabe-Fehler behandeln
  // -------------------------
  if ($error !="") {
    // Komma am Ende entfernen
    // ========================
    $error=ereg_replace(",$" , "<br>" , $error);
    $error = "Folgende Felder wurde nicht ausgefüllt: <br>\n".$error;
    ?>
    <tr>
      <td>&nbsp;</td>
      <td colspan="2"><font color="Red"><?php echo $error; ?></font></td>
    </tr>
    <?php
  }
  ?>

  <tr>
	<td>&nbsp;Name :</td>
    <td>&nbsp;</td>
	<td><input type="text" name="name" value="<?php if (isset($name)) {echo $name;}?>" ></td>
  </tr>

  <tr>
	<td>&nbsp;Email:</td>
    <td>&nbsp;</td>
	<td><input type="text" name="email" value="<?php if (isset($email)) {echo $email;}?>" ></td>
  </tr>

  <tr>
    <td>PLZ&nbsp;/&nbsp;Ort:</td>
    <td><input type="text" name="plz" size="5" maxlength="5" value="<?php if (isset($plz)) {echo $plz;}?>"></td>
    <td><input type="text" name="ort" value="<?php if (isset($ort)) {echo $ort;}?>"></td>
  </tr>

  <tr>
	<td>Stra&szlig;e:</td>
    <td>&nbsp;</td>
	<td><input type="text" name="strasse" value="<?php if (isset($strasse)) {echo $strasse;}?>" ></td>
  </tr>

  <tr>
	<td>Telefon:</td>
    <td>&nbsp;</td>
	<td><input type="text" name="telefon" value="<?php if (isset($telefon)) {echo $telefon;}?>" ></td>
  </tr>

  <tr>
	<td>Kontaktaufnahme:</td>
    <td>&nbsp;</td>
	<td>
      <table cellpadding=0 border=0>
		<td><input type=checkbox  name="kontakt_1" value="1" <?php if (isset($kontakt_1)) {if ($kontakt_1==1) {echo "CHECKED";}}?>></td>
		<td> per Email</td>
		<td><input type=checkbox  name="kontakt_2" value="1" <?php if (isset($kontakt_2)) {if ($kontakt_2==1) {echo "CHECKED";}}?>></td>
		<td> rufen Sie mich an</td>
      </table>
    </td>
  </tr>

  <tr>
	<td>Ihre Nachricht:</td>
    <td colspan="2"><textarea cols=30 rows=6  name="comment"><?php if (isset($comment)) {echo $comment;}?></textarea></td>
  </tr>

  <tr>
    <td>&nbsp;</td>
    <td colspan="2" align="center"><input type="submit" value="Abschicken">&nbsp;<input type="reset" value="Zurücksetzen"></td>
  </tr>
  </table>
  </form>
<?php
}
?>

</div>
</body>
</html>
